package com.eliaovideo.videoline.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.eliaovideo.videoline.msg.modle.Msg;
import com.eliaovideo.videoline.modle.ReadFile;
import com.eliaovideo.videoline.modle.JsonData;

import com.eliaovideo.videoline.dao.MsgDao;
import com.eliaovideo.videoline.dao.ReadFileDao;
import com.eliaovideo.videoline.dao.JsonDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig msgDaoConfig;
    private final DaoConfig readFileDaoConfig;
    private final DaoConfig jsonDataDaoConfig;

    private final MsgDao msgDao;
    private final ReadFileDao readFileDao;
    private final JsonDataDao jsonDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        msgDaoConfig = daoConfigMap.get(MsgDao.class).clone();
        msgDaoConfig.initIdentityScope(type);

        readFileDaoConfig = daoConfigMap.get(ReadFileDao.class).clone();
        readFileDaoConfig.initIdentityScope(type);

        jsonDataDaoConfig = daoConfigMap.get(JsonDataDao.class).clone();
        jsonDataDaoConfig.initIdentityScope(type);

        msgDao = new MsgDao(msgDaoConfig, this);
        readFileDao = new ReadFileDao(readFileDaoConfig, this);
        jsonDataDao = new JsonDataDao(jsonDataDaoConfig, this);

        registerDao(Msg.class, msgDao);
        registerDao(ReadFile.class, readFileDao);
        registerDao(JsonData.class, jsonDataDao);
    }
    
    public void clear() {
        msgDaoConfig.getIdentityScope().clear();
        readFileDaoConfig.getIdentityScope().clear();
        jsonDataDaoConfig.getIdentityScope().clear();
    }

    public MsgDao getMsgDao() {
        return msgDao;
    }

    public ReadFileDao getReadFileDao() {
        return readFileDao;
    }

    public JsonDataDao getJsonDataDao() {
        return jsonDataDao;
    }

}
